version: "3.5"

services:

  nginx:
    image: nginx:latest
    ports:
      - 127.0.0.1:83:80
    volumes:
      - .:/var/www/html
      - ./docker/config/nginx:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - .:/var/www/html

  postgres:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=redis_backup
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
    - 5432:5432

  phppgadmin:
    image: dockage/phppgadmin:latest
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=redis_backup
    restart: always
    ports:
      - 8087:80
      - "443:443"
    links:
      - postgres
